###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/bookings

###
GET http://localhost:3000/api/fleet

###
GET http://localhost:3000/api/locations

###
GET http://localhost:3000/api/payments

###
GET http://localhost:3000/api/vehicles
